package com.scandit.reactnative

const val KEY_CAMERA_SWITCH_NEVER = "CAMERA_SWITCH_NEVER"
const val KEY_CAMERA_SWITCH_ON_TABLET = "CAMERA_SWITCH_ON_TABLET"
const val KEY_CAMERA_SWITCH_ALWAYS = "CAMERA_SWITCH_ALWAYS"
const val KEY_MATRIX_SCAN_STATE_LOCALIZED = "MATRIX_SCAN_STATE_LOCALIZED"
const val KEY_MATRIX_SCAN_STATE_RECOGNIZED = "MATRIX_SCAN_STATE_RECOGNIZED"
const val KEY_MATRIX_SCAN_STATE_REJECTED = "MATRIX_SCAN_STATE_REJECTED"
const val KEY_GUI_STYLE_DEFAULT = "GUI_STYLE_DEFAULT"
const val KEY_GUI_STYLE_LASER = "GUI_STYLE_LASER"
const val KEY_GUI_STYLE_NONE = "GUI_STYLE_NONE"
const val KEY_GUI_STYLE_MATRIX_SCAN = "GUI_STYLE_MATRIX_SCAN"
const val KEY_GUI_STYLE_LOCATIONS_ONLY = "GUI_STYLE_LOCATIONS_ONLY"
